// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entities.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240111125546_Second")]
    partial class Second
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactId"));

                    b.Property<string>("ContactName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhoneNummber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ContactId");

                    b.HasIndex("UserID");

                    b.ToTable("Contacts", (string)null);

                    b.HasData(
                        new
                        {
                            ContactId = 1,
                            ContactName = "Marko Maric",
                            PhoneNummber = "+38172637781",
                            UserID = 1
                        },
                        new
                        {
                            ContactId = 2,
                            ContactName = "Pera Peric",
                            PhoneNummber = "+3899999",
                            UserID = 1
                        },
                        new
                        {
                            ContactId = 3,
                            ContactName = "Sima Simic",
                            PhoneNummber = "+38112345",
                            UserID = 1
                        },
                        new
                        {
                            ContactId = 4,
                            ContactName = "Marko Maric",
                            PhoneNummber = "+38172637781",
                            UserID = 2
                        },
                        new
                        {
                            ContactId = 5,
                            ContactName = "Marko Maric",
                            PhoneNummber = "+38172637781",
                            UserID = 3
                        },
                        new
                        {
                            ContactId = 6,
                            ContactName = "Pera Peric",
                            PhoneNummber = "+3899999",
                            UserID = 2
                        },
                        new
                        {
                            ContactId = 7,
                            ContactName = "Sima Simic",
                            PhoneNummber = "+38112345",
                            UserID = 2
                        },
                        new
                        {
                            ContactId = 8,
                            ContactName = "Tosa Tosic",
                            PhoneNummber = "+9991111",
                            UserID = 3
                        });
                });

            modelBuilder.Entity("Entities.User", b =>
                {
                    b.Property<int?>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("UserID"));

                    b.Property<string>("Email")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("PhoneNummber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("UserName")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("UserID");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Email = "kristijan@gmail.com",
                            PhoneNummber = "+38177733",
                            UserName = "KristijanMn"
                        },
                        new
                        {
                            UserID = 2,
                            Email = "Markom@gmail.com",
                            PhoneNummber = "+38172637781",
                            UserName = "markoM"
                        },
                        new
                        {
                            UserID = 3,
                            Email = "simasdm@gmail.com",
                            PhoneNummber = "+38112345",
                            UserName = "Simasd"
                        });
                });

            modelBuilder.Entity("Entities.Contact", b =>
                {
                    b.HasOne("Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
